// Auto-generated from `commands.manifest.json` (Layer 0 / Task 0).
// Do not edit by hand — re-run `bash scripts/gen-command-manifest.sh` then
// `bash scripts/gen-web-commands.sh` to refresh.
//
// This module maps every Tauri command surface (`#[tauri::command]`) to its
// Web HTTP route. The adapter looks up command specs by name at runtime.

import { defineCommands, registerCommands } from "./adapter"

const cmds = defineCommands({
  add_custom_endpoint: { method: "POST", path: "/api/system/add_custom_endpoint" },
  add_provider: { method: "POST", path: "/api/providers/add-provider" },
  add_skill_repo: { method: "POST", path: "/api/skills/add-skill-repo" },
  add_to_failover_queue: { method: "POST", path: "/api/failover/add-to-failover-queue" },
  apply_claude_onboarding_skip: { method: "POST", path: "/api/system/apply_claude_onboarding_skip" },
  apply_claude_plugin_config: { method: "POST", path: "/api/config/apply-claude-plugin-config" },
  auth_get_status: { method: "POST", path: "/api/auth/auth-get-status" },
  auth_list_accounts: { method: "POST", path: "/api/auth/auth-list-accounts" },
  auth_logout: { method: "POST", path: "/api/auth/auth-logout" },
  auth_poll_for_account: { method: "POST", path: "/api/auth/auth-poll-for-account" },
  auth_remove_account: { method: "POST", path: "/api/auth/auth-remove-account" },
  auth_set_default_account: { method: "POST", path: "/api/auth/auth-set-default-account" },
  auth_start_login: { method: "POST", path: "/api/auth/auth-start-login" },
  check_env_conflicts: { method: "GET", path: "/api/env/check-env-conflicts" },
  check_for_updates: { method: "POST", path: "/api/system/check_for_updates" },
  check_provider_limits: { method: "GET", path: "/api/providers/check-provider-limits" },
  check_skill_updates: { method: "GET", path: "/api/skills/check-skill-updates" },
  clear_claude_onboarding_skip: { method: "POST", path: "/api/system/clear_claude_onboarding_skip" },
  copilot_get_auth_status: { method: "POST", path: "/api/auth/copilot-get-auth-status", unsupported: true as const },
  copilot_get_models: { method: "POST", path: "/api/copilot/copilot-get-models", unsupported: true as const },
  copilot_get_models_for_account: { method: "POST", path: "/api/copilot/copilot-get-models-for-account", unsupported: true as const },
  copilot_get_token: { method: "POST", path: "/api/copilot/copilot-get-token", unsupported: true as const },
  copilot_get_token_for_account: { method: "POST", path: "/api/copilot/copilot-get-token-for-account", unsupported: true as const },
  copilot_get_usage: { method: "POST", path: "/api/copilot/copilot-get-usage", unsupported: true as const },
  copilot_get_usage_for_account: { method: "POST", path: "/api/copilot/copilot-get-usage-for-account", unsupported: true as const },
  copilot_is_authenticated: { method: "POST", path: "/api/auth/copilot-is-authenticated", unsupported: true as const },
  copilot_list_accounts: { method: "POST", path: "/api/copilot/copilot-list-accounts", unsupported: true as const },
  copilot_logout: { method: "POST", path: "/api/copilot/copilot-logout", unsupported: true as const },
  copilot_poll_for_account: { method: "POST", path: "/api/copilot/copilot-poll-for-account", unsupported: true as const },
  copilot_poll_for_auth: { method: "POST", path: "/api/auth/copilot-poll-for-auth", unsupported: true as const },
  copilot_remove_account: { method: "POST", path: "/api/copilot/copilot-remove-account", unsupported: true as const },
  copilot_set_default_account: { method: "POST", path: "/api/copilot/copilot-set-default-account", unsupported: true as const },
  copilot_start_device_flow: { method: "POST", path: "/api/copilot/copilot-start-device-flow", unsupported: true as const },
  copy_text_to_clipboard: { method: "POST", path: "/api/system/copy_text_to_clipboard", unsupported: true as const },
  create_db_backup: { method: "POST", path: "/api/backups/create-db-backup" },
  delete_claude_mcp_server: { method: "DELETE", path: "/api/mcp/delete-claude-mcp-server" },
  delete_daily_memory_file: { method: "POST", path: "/api/system/delete_daily_memory_file" },
  delete_db_backup: { method: "DELETE", path: "/api/backups/delete-db-backup" },
  delete_env_vars: { method: "DELETE", path: "/api/env/delete-env-vars", bodyParams: true },
  delete_mcp_server: { method: "DELETE", path: "/api/mcp/delete-mcp-server" },
  delete_mcp_server_in_config: { method: "DELETE", path: "/api/config/delete-mcp-server-in-config" },
  delete_model_pricing: { method: "POST", path: "/api/system/delete_model_pricing" },
  delete_prompt: { method: "DELETE", path: "/api/prompts/delete-prompt" },
  delete_provider: { method: "DELETE", path: "/api/providers/delete-provider" },
  delete_session: { method: "DELETE", path: "/api/sessions/delete-session" },
  delete_sessions: { method: "DELETE", path: "/api/sessions/delete-sessions", bodyParams: true },
  delete_skill_backup: { method: "DELETE", path: "/api/backups/delete-skill-backup" },
  delete_universal_provider: { method: "DELETE", path: "/api/providers/delete-universal-provider" },
  disable_current_omo: { method: "POST", path: "/api/omo/disable-current-omo" },
  disable_current_omo_slim: { method: "POST", path: "/api/omo/disable-current-omo-slim" },
  discover_available_skills: { method: "POST", path: "/api/skills/discover-available-skills" },
  enable_prompt: { method: "POST", path: "/api/prompts/enable-prompt" },
  enter_lightweight_mode: { method: "POST", path: "/api/system/enter-lightweight-mode" },
  exit_lightweight_mode: { method: "POST", path: "/api/system/exit-lightweight-mode" },
  export_config_to_file: { method: "POST", path: "/api/config/export-config-to-file", webReplacement: true as const },
  extract_common_config_snippet: { method: "POST", path: "/api/config/extract-common-config-snippet" },
  fetch_models_for_config: { method: "GET", path: "/api/config/fetch-models-for-config" },
  get_app_config_dir_override: { method: "GET", path: "/api/config/get-app-config-dir-override" },
  get_app_config_path: { method: "GET", path: "/api/config/get-app-config-path" },
  get_auto_failover_enabled: { method: "GET", path: "/api/failover/get-auto-failover-enabled" },
  get_auto_launch_status: { method: "POST", path: "/api/system/get_auto_launch_status", unsupported: true as const },
  get_available_providers_for_failover: { method: "GET", path: "/api/failover/get-available-providers-for-failover" },
  get_balance: { method: "GET", path: "/api/usage/get-balance" },
  get_circuit_breaker_config: { method: "GET", path: "/api/config/get-circuit-breaker-config" },
  get_circuit_breaker_stats: { method: "POST", path: "/api/system/get_circuit_breaker_stats" },
  get_claude_code_config_path: { method: "GET", path: "/api/config/get-claude-code-config-path" },
  get_claude_common_config_snippet: { method: "GET", path: "/api/config/get-claude-common-config-snippet" },
  get_claude_config_status: { method: "GET", path: "/api/config/get-claude-config-status" },
  get_claude_mcp_status: { method: "GET", path: "/api/mcp/get-claude-mcp-status" },
  get_claude_plugin_status: { method: "GET", path: "/api/vscode/get-claude-plugin-status", unsupported: true as const },
  get_codex_oauth_quota: { method: "GET", path: "/api/auth/get-codex-oauth-quota", unsupported: true as const },
  get_coding_plan_quota: { method: "GET", path: "/api/usage/get-coding-plan-quota" },
  get_common_config_snippet: { method: "GET", path: "/api/config/get-common-config-snippet" },
  get_config_dir: { method: "GET", path: "/api/config/get-config-dir" },
  get_config_status: { method: "GET", path: "/api/config/get-config-status" },
  get_copilot_optimizer_config: { method: "GET", path: "/api/config/get-copilot-optimizer-config", unsupported: true as const },
  get_current_omo_provider_id: { method: "GET", path: "/api/omo/get-current-omo-provider-id" },
  get_current_omo_slim_provider_id: { method: "GET", path: "/api/omo/get-current-omo-slim-provider-id" },
  get_current_prompt_file_content: { method: "GET", path: "/api/prompts/get-current-prompt-file-content" },
  get_current_provider: { method: "GET", path: "/api/providers/get-current-provider" },
  get_custom_endpoints: { method: "POST", path: "/api/system/get_custom_endpoints" },
  get_default_cost_multiplier: { method: "POST", path: "/api/system/get_default_cost_multiplier" },
  get_failover_queue: { method: "GET", path: "/api/failover/get-failover-queue" },
  get_global_proxy_config: { method: "GET", path: "/api/config/get-global-proxy-config" },
  get_global_proxy_url: { method: "GET", path: "/api/global-proxy/get-global-proxy-url" },
  get_hermes_live_provider: { method: "GET", path: "/api/hermes/get-hermes-live-provider" },
  get_hermes_live_provider_ids: { method: "GET", path: "/api/hermes/get-hermes-live-provider-ids" },
  get_hermes_memory: { method: "GET", path: "/api/hermes/get-hermes-memory" },
  get_hermes_memory_limits: { method: "GET", path: "/api/hermes/get-hermes-memory-limits" },
  get_hermes_model_config: { method: "GET", path: "/api/config/get-hermes-model-config" },
  get_init_error: { method: "POST", path: "/api/system/get_init_error" },
  get_installed_skills: { method: "GET", path: "/api/skills/get-installed-skills" },
  get_log_config: { method: "GET", path: "/api/config/get-log-config" },
  get_mcp_config: { method: "GET", path: "/api/config/get-mcp-config" },
  get_mcp_servers: { method: "GET", path: "/api/mcp/get-mcp-servers" },
  get_migration_result: { method: "POST", path: "/api/system/get_migration_result" },
  get_model_pricing: { method: "POST", path: "/api/system/get_model_pricing" },
  get_model_stats: { method: "POST", path: "/api/system/get_model_stats" },
  get_openclaw_agents_defaults: { method: "GET", path: "/api/openclaw/get-openclaw-agents-defaults" },
  get_openclaw_default_model: { method: "GET", path: "/api/openclaw/get-openclaw-default-model" },
  get_openclaw_env: { method: "GET", path: "/api/env/get-openclaw-env" },
  get_openclaw_live_provider: { method: "GET", path: "/api/openclaw/get-openclaw-live-provider" },
  get_openclaw_live_provider_ids: { method: "GET", path: "/api/openclaw/get-openclaw-live-provider-ids" },
  get_openclaw_model_catalog: { method: "GET", path: "/api/openclaw/get-openclaw-model-catalog" },
  get_openclaw_tools: { method: "GET", path: "/api/openclaw/get-openclaw-tools" },
  get_opencode_live_provider_ids: { method: "GET", path: "/api/providers/get-opencode-live-provider-ids" },
  get_optimizer_config: { method: "GET", path: "/api/config/get-optimizer-config" },
  get_pricing_model_source: { method: "POST", path: "/api/system/get_pricing_model_source" },
  get_prompts: { method: "GET", path: "/api/prompts/get-prompts" },
  get_provider_health: { method: "GET", path: "/api/providers/get-provider-health" },
  get_provider_stats: { method: "GET", path: "/api/providers/get-provider-stats" },
  get_providers: { method: "GET", path: "/api/providers/get-providers" },
  get_proxy_config: { method: "GET", path: "/api/config/get-proxy-config" },
  get_proxy_config_for_app: { method: "GET", path: "/api/config/get-proxy-config-for-app" },
  get_proxy_status: { method: "GET", path: "/api/proxy/get-proxy-status" },
  get_proxy_takeover_status: { method: "GET", path: "/api/proxy/get-proxy-takeover-status" },
  get_rectifier_config: { method: "GET", path: "/api/config/get-rectifier-config" },
  get_request_detail: { method: "POST", path: "/api/system/get_request_detail" },
  get_request_logs: { method: "POST", path: "/api/system/get_request_logs" },
  get_session_messages: { method: "GET", path: "/api/sessions/get-session-messages" },
  get_settings: { method: "GET", path: "/api/settings/get-settings" },
  get_skill_backups: { method: "GET", path: "/api/backups/get-skill-backups" },
  get_skill_repos: { method: "GET", path: "/api/skills/get-skill-repos" },
  get_skills: { method: "GET", path: "/api/skills/get-skills" },
  get_skills_for_app: { method: "GET", path: "/api/skills/get-skills-for-app" },
  get_skills_migration_result: { method: "GET", path: "/api/skills/get-skills-migration-result" },
  get_stream_check_config: { method: "GET", path: "/api/config/get-stream-check-config" },
  get_subscription_quota: { method: "GET", path: "/api/subscription/get-subscription-quota" },
  get_tool_versions: { method: "POST", path: "/api/system/get_tool_versions" },
  get_universal_provider: { method: "GET", path: "/api/providers/get-universal-provider" },
  get_universal_providers: { method: "GET", path: "/api/providers/get-universal-providers" },
  get_upstream_proxy_status: { method: "GET", path: "/api/proxy/get-upstream-proxy-status" },
  get_usage_data_sources: { method: "GET", path: "/api/usage/get-usage-data-sources" },
  get_usage_summary: { method: "GET", path: "/api/usage/get-usage-summary" },
  get_usage_trends: { method: "GET", path: "/api/usage/get-usage-trends" },
  import_config_from_file: { method: "POST", path: "/api/config/import-config-from-file", webReplacement: true as const },
  import_default_config: { method: "POST", path: "/api/config/import-default-config" },
  import_from_deeplink: { method: "POST", path: "/api/deeplink/import-from-deeplink" },
  import_from_deeplink_unified: { method: "POST", path: "/api/deeplink/import-from-deeplink-unified" },
  import_hermes_providers_from_live: { method: "POST", path: "/api/hermes/import-hermes-providers-from-live" },
  import_mcp_from_apps: { method: "POST", path: "/api/mcp/import-mcp-from-apps" },
  import_openclaw_providers_from_live: { method: "POST", path: "/api/openclaw/import-openclaw-providers-from-live" },
  import_opencode_providers_from_live: { method: "POST", path: "/api/providers/import-opencode-providers-from-live" },
  import_prompt_from_file: { method: "POST", path: "/api/prompts/import-prompt-from-file", webReplacement: true as const },
  import_skills_from_apps: { method: "POST", path: "/api/skills/import-skills-from-apps" },
  install_skill: { method: "POST", path: "/api/skills/install-skill" },
  install_skill_for_app: { method: "POST", path: "/api/skills/install-skill-for-app" },
  install_skill_unified: { method: "POST", path: "/api/skills/install-skill-unified" },
  install_skills_from_zip: { method: "POST", path: "/api/skills/install-skills-from-zip", webReplacement: true as const },
  is_claude_plugin_applied: { method: "GET", path: "/api/vscode/is-claude-plugin-applied", unsupported: true as const },
  is_lightweight_mode: { method: "GET", path: "/api/system/is-lightweight-mode" },
  is_live_takeover_active: { method: "POST", path: "/api/system/is_live_takeover_active" },
  is_portable_mode: { method: "POST", path: "/api/system/is_portable_mode" },
  is_proxy_running: { method: "GET", path: "/api/proxy/is-proxy-running" },
  launch_hermes_dashboard: { method: "POST", path: "/api/hermes/launch-hermes-dashboard" },
  launch_session_terminal: { method: "POST", path: "/api/sessions/launch-session-terminal" },
  list_daily_memory_files: { method: "POST", path: "/api/system/list_daily_memory_files" },
  list_db_backups: { method: "GET", path: "/api/backups/list-db-backups" },
  list_sessions: { method: "GET", path: "/api/sessions/list-sessions" },
  merge_deeplink_config: { method: "POST", path: "/api/config/merge-deeplink-config" },
  migrate_skill_storage: { method: "POST", path: "/api/skills/migrate-skill-storage" },
  open_app_config_folder: { method: "POST", path: "/api/config/open-app-config-folder", unsupported: true as const },
  open_config_folder: { method: "POST", path: "/api/config/open-config-folder", unsupported: true as const },
  open_external: { method: "POST", path: "/api/system/open_external" },
  open_file_dialog: { method: "POST", path: "/api/system/open_file_dialog", webReplacement: true as const },
  open_hermes_web_ui: { method: "POST", path: "/api/hermes/open-hermes-web-ui" },
  open_provider_terminal: { method: "POST", path: "/api/providers/open-provider-terminal", unsupported: true as const },
  open_workspace_directory: { method: "POST", path: "/api/workspace/open-workspace-directory", unsupported: true as const },
  open_zip_file_dialog: { method: "POST", path: "/api/system/open_zip_file_dialog", webReplacement: true as const },
  parse_deeplink: { method: "POST", path: "/api/deeplink/parse-deeplink" },
  pick_directory: { method: "POST", path: "/api/system/pick_directory", unsupported: true as const },
  queryProviderUsage: { method: "POST", path: "/api/providers/queryproviderusage" },
  read_claude_mcp_config: { method: "GET", path: "/api/config/read-claude-mcp-config" },
  read_claude_plugin_config: { method: "GET", path: "/api/config/read-claude-plugin-config" },
  read_daily_memory_file: { method: "POST", path: "/api/system/read_daily_memory_file" },
  read_live_provider_settings: { method: "GET", path: "/api/providers/read-live-provider-settings" },
  read_omo_local_file: { method: "GET", path: "/api/omo/read-omo-local-file" },
  read_omo_slim_local_file: { method: "GET", path: "/api/omo/read-omo-slim-local-file" },
  read_workspace_file: { method: "GET", path: "/api/workspace/read-workspace-file" },
  remove_custom_endpoint: { method: "POST", path: "/api/system/remove_custom_endpoint" },
  remove_from_failover_queue: { method: "DELETE", path: "/api/failover/remove-from-failover-queue" },
  remove_provider_from_live_config: { method: "DELETE", path: "/api/config/remove-provider-from-live-config" },
  remove_skill_repo: { method: "DELETE", path: "/api/skills/remove-skill-repo" },
  rename_db_backup: { method: "POST", path: "/api/backups/rename-db-backup" },
  reset_circuit_breaker: { method: "POST", path: "/api/system/reset_circuit_breaker" },
  restart_app: { method: "POST", path: "/api/system/restart_app" },
  restore_db_backup: { method: "POST", path: "/api/backups/restore-db-backup" },
  restore_env_backup: { method: "POST", path: "/api/backups/restore-env-backup" },
  restore_skill_backup: { method: "POST", path: "/api/backups/restore-skill-backup" },
  save_file_dialog: { method: "POST", path: "/api/system/save_file_dialog", webReplacement: true as const },
  save_settings: { method: "PUT", path: "/api/settings/save-settings" },
  save_stream_check_config: { method: "PUT", path: "/api/config/save-stream-check-config" },
  scan_local_proxies: { method: "POST", path: "/api/system/scan_local_proxies" },
  scan_openclaw_config_health: { method: "GET", path: "/api/config/scan-openclaw-config-health" },
  scan_unmanaged_skills: { method: "GET", path: "/api/skills/scan-unmanaged-skills" },
  search_daily_memory_files: { method: "POST", path: "/api/system/search_daily_memory_files" },
  search_skills_sh: { method: "POST", path: "/api/skills/search-skills-sh" },
  set_app_config_dir_override: { method: "PUT", path: "/api/config/set-app-config-dir-override" },
  set_auto_failover_enabled: { method: "PUT", path: "/api/failover/set-auto-failover-enabled" },
  set_auto_launch: { method: "POST", path: "/api/system/set_auto_launch", unsupported: true as const },
  set_claude_common_config_snippet: { method: "PUT", path: "/api/config/set-claude-common-config-snippet" },
  set_common_config_snippet: { method: "PUT", path: "/api/config/set-common-config-snippet" },
  set_copilot_optimizer_config: { method: "PUT", path: "/api/config/set-copilot-optimizer-config", unsupported: true as const },
  set_default_cost_multiplier: { method: "POST", path: "/api/system/set_default_cost_multiplier" },
  set_global_proxy_url: { method: "PUT", path: "/api/global-proxy/set-global-proxy-url" },
  set_hermes_memory: { method: "PUT", path: "/api/hermes/set-hermes-memory" },
  set_hermes_memory_enabled: { method: "PUT", path: "/api/hermes/set-hermes-memory-enabled" },
  set_log_config: { method: "PUT", path: "/api/config/set-log-config" },
  set_mcp_enabled: { method: "PUT", path: "/api/mcp/set-mcp-enabled" },
  set_openclaw_agents_defaults: { method: "PUT", path: "/api/openclaw/set-openclaw-agents-defaults" },
  set_openclaw_default_model: { method: "PUT", path: "/api/openclaw/set-openclaw-default-model" },
  set_openclaw_env: { method: "PUT", path: "/api/env/set-openclaw-env" },
  set_openclaw_model_catalog: { method: "PUT", path: "/api/openclaw/set-openclaw-model-catalog" },
  set_openclaw_tools: { method: "PUT", path: "/api/openclaw/set-openclaw-tools" },
  set_optimizer_config: { method: "PUT", path: "/api/config/set-optimizer-config" },
  set_pricing_model_source: { method: "POST", path: "/api/system/set_pricing_model_source" },
  set_proxy_takeover_for_app: { method: "PUT", path: "/api/proxy/set-proxy-takeover-for-app" },
  set_rectifier_config: { method: "PUT", path: "/api/config/set-rectifier-config" },
  set_window_theme: { method: "POST", path: "/api/system/set_window_theme", unsupported: true as const },
  start_proxy_server: { method: "POST", path: "/api/proxy/start-proxy-server" },
  stop_proxy_with_restore: { method: "POST", path: "/api/proxy/stop-proxy-with-restore" },
  stream_check_all_providers: { method: "POST", path: "/api/providers/stream-check-all-providers" },
  stream_check_provider: { method: "POST", path: "/api/providers/stream-check-provider" },
  switch_provider: { method: "POST", path: "/api/providers/switch-provider" },
  switch_proxy_provider: { method: "POST", path: "/api/providers/switch-proxy-provider" },
  sync_current_providers_live: { method: "POST", path: "/api/providers/sync-current-providers-live" },
  sync_session_usage: { method: "POST", path: "/api/sessions/sync-session-usage" },
  sync_universal_provider: { method: "POST", path: "/api/providers/sync-universal-provider" },
  testUsageScript: { method: "POST", path: "/api/usage/testusagescript" },
  test_api_endpoints: { method: "POST", path: "/api/system/test_api_endpoints" },
  test_proxy_url: { method: "POST", path: "/api/proxy/test-proxy-url" },
  toggle_mcp_app: { method: "POST", path: "/api/mcp/toggle-mcp-app" },
  toggle_skill_app: { method: "POST", path: "/api/skills/toggle-skill-app" },
  uninstall_skill: { method: "POST", path: "/api/skills/uninstall-skill" },
  uninstall_skill_for_app: { method: "POST", path: "/api/skills/uninstall-skill-for-app" },
  uninstall_skill_unified: { method: "POST", path: "/api/skills/uninstall-skill-unified" },
  update_circuit_breaker_config: { method: "PUT", path: "/api/config/update-circuit-breaker-config" },
  update_endpoint_last_used: { method: "POST", path: "/api/system/update_endpoint_last_used" },
  update_global_proxy_config: { method: "PUT", path: "/api/config/update-global-proxy-config" },
  update_model_pricing: { method: "POST", path: "/api/system/update_model_pricing" },
  update_provider: { method: "PUT", path: "/api/providers/update-provider" },
  update_providers_sort_order: { method: "PUT", path: "/api/providers/update-providers-sort-order" },
  update_proxy_config: { method: "PUT", path: "/api/config/update-proxy-config" },
  update_proxy_config_for_app: { method: "PUT", path: "/api/config/update-proxy-config-for-app" },
  update_skill: { method: "PUT", path: "/api/skills/update-skill" },
  update_tray_menu: { method: "POST", path: "/api/system/update_tray_menu", unsupported: true as const },
  upsert_claude_mcp_server: { method: "POST", path: "/api/mcp/upsert-claude-mcp-server" },
  upsert_mcp_server: { method: "POST", path: "/api/mcp/upsert-mcp-server" },
  upsert_mcp_server_in_config: { method: "POST", path: "/api/config/upsert-mcp-server-in-config" },
  upsert_prompt: { method: "POST", path: "/api/prompts/upsert-prompt" },
  upsert_universal_provider: { method: "POST", path: "/api/providers/upsert-universal-provider" },
  validate_mcp_command: { method: "POST", path: "/api/mcp/validate-mcp-command" },
  webdav_sync_download: { method: "POST", path: "/api/webdav/webdav-sync-download" },
  webdav_sync_fetch_remote_info: { method: "POST", path: "/api/webdav/webdav-sync-fetch-remote-info" },
  webdav_sync_save_settings: { method: "POST", path: "/api/settings/webdav-sync-save-settings" },
  webdav_sync_upload: { method: "POST", path: "/api/webdav/webdav-sync-upload" },
  webdav_test_connection: { method: "POST", path: "/api/webdav/webdav-test-connection" },
  write_daily_memory_file: { method: "POST", path: "/api/system/write_daily_memory_file" },
  write_workspace_file: { method: "PUT", path: "/api/workspace/write-workspace-file" },
})

registerCommands(cmds)

export type WebCommandName = keyof typeof cmds
export { cmds as webCommandRegistry }
